env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash
    
task:
    name: lavender
    timeout_in: 4h
    container:
      image: apon77/aosp:cirrus
      cpu: 16
      memory: 48g
    
    sync_script:
      - bash sync.sh
    build_script:
      - bash build_rom.sh
